name: Laravel Code Formatting

on: [push]

jobs:
  laravel-code-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Composer Install
        run: composer install

      - name: Run Laravel Pint
        run: ./vendor/bin/pint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Check Laravel Code Formatting
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

